name: Build and deploy ASP app to Azure Web App - fardeenportfoliowebsite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read  # Required for actions/checkout
      id-token: write # Required for requesting the JWT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7F9E78751304873AB223C800E745503 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5585D8FD2F764D9DAB4DF868F350A1AD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1D43E53172F74D70B48CBC65FC6A730A }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ${{ github.workspace }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fardeenportfoliowebsite'
          slot-name: 'dev'
          package: ${{ github.workspace}} 
